name: ci_splinart_2026

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]

jobs:
  # Deploy job
  deploy:
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: production-deploiement
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - id: install_pandoc
        run: sudo apt-get install pandoc
      - name: Cloner le depot
        uses: actions/checkout@v7

      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Run sphinx api doc
        run: |
          uv run --active sphinx-apidoc -f -o docs_md/source/api src/splinart
          cd ./docs_md
          uv run make html
          tree -f build
      - name: Deploy to GitHub Pages

        id: deployment
        uses: sphinx-notes/pages@v3
        with:
          python_version: 3.13
          documentation_path: /docs_md/source
      - name: verify file html availables
        run: |
          tree -f /docs/build
